fix: AttributeError Field self_paced doesn't exist
```
2025-12-15 23:28:19,515 INFO 13 [tracking] [user 23] [ip 98.181.3.75] logger.py:41 - {"name": "/api/course_home/course_metadata/course-v1:Hadrian+CMM1+CMM", "context": {"user_id": 23, "path": "/api/course_home/course_metadata/course-v1:Hadrian+CMM1+CMM", "course_id": "", "org_id": "", "enterprise_uuid": ""}, "username": "test123", "session": "ad22c63abfbae7a222b67dd47d23a8b0", "ip": "98.181.3.75", "agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36", "host": "learning.staging.cloud.hadrian.co", "referer": "https://apps.learning.staging.cloud.hadrian.co/", "accept_language": "en-US,en;q=0.9", "event": "{\"GET\": {\"browser_timezone\": [\"America/Los_Angeles\"]}, \"POST\": {}}", "time": "2025-12-15T23:28:19.514814+00:00", "event_type": "/api/course_home/course_metadata/course-v1:Hadrian+CMM1+CMM", "event_source": "server", "page": null}
2025-12-15 23:28:19,635 ERROR 14 [root] [user None] [ip None] signals.py:22 - Uncaught exception from None
Traceback (most recent call last):
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/block_structure.py", line 304, in __getattr__
    return self.fields[field_name]
           ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'self_paced'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/openedx/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyenv/versions/3.11.8/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/openedx/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/openedx/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/lms/djangoapps/course_home_api/outline/views.py", line 249, in get
    course_blocks = get_course_outline_block_tree(request, course_key_string, request.user)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/openedx/core/lib/cache_utils.py", line 74, in decorator
    result = wrapped(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/openedx/features/course_experience/utils.py", line 94, in get_course_outline_block_tree
    all_blocks = get_blocks(
                 ^^^^^^^^^^^
  File "/openedx/edx-platform/lms/djangoapps/course_api/blocks/api.py", line 122, in get_blocks
    blocks = course_blocks_api.get_course_blocks(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/lms/djangoapps/course_blocks/api.py", line 107, in get_course_blocks
    return get_block_structure_manager(starting_block_usage_key.course_key).get_transformed(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/manager.py", line 80, in get_transformed
    transformers.transform(block_structure)
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/transformers.py", line 114, in transform
    self._transform_without_filters(block_structure)
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/transformers.py", line 140, in _transform_without_filters
    transformer.transform(self.usage_info, block_structure)
  File "/openedx/edx-platform/lms/djangoapps/course_blocks/transformers/hidden_content.py", line 95, in transform
    block_structure.remove_block_traversal(lambda block_key: self._is_block_hidden(block_structure, block_key))
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/block_structure.py", line 704, in remove_block_traversal
    self.filter_topological_traversal(
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/block_structure.py", line 729, in filter_topological_traversal
    for _ in self.topological_traversal(filter_func=filter_func, **kwargs):
  File "/openedx/edx-platform/openedx/core/lib/graph_traversals.py", line 329, in _traverse_generic
    should_yield_node = filter_func(current_node)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/block_structure.py", line 685, in retain_or_remove
    if removal_condition(block_key):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/lms/djangoapps/course_blocks/transformers/hidden_content.py", line 95, in <lambda>
    block_structure.remove_block_traversal(lambda block_key: self._is_block_hidden(block_structure, block_key))
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/lms/djangoapps/course_blocks/transformers/hidden_content.py", line 103, in _is_block_hidden
    self_paced = block_structure[block_structure.root_block_usage_key].self_paced
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/block_structure.py", line 306, in __getattr__
    raise AttributeError(f"Field {field_name} does not exist")  # lint-amnesty, pylint: disable=raise-missing-from
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Field self_paced does not exist
2025-12-15 23:28:19,679 INFO 14 [edx.footer] [user 23] [ip 98.181.3.75] api.py:479 - images/logo.png
2025-12-15 23:28:19,694 ERROR 14 [django.request] [user 23] [ip 98.181.3.75] log.py:241 - Internal Server Error: /api/course_home/outline/course-v1:Hadrian+CMM1+CMM
Traceback (most recent call last):
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/block_structure.py", line 304, in __getattr__
    return self.fields[field_name]
           ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'self_paced'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/openedx/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pyenv/versions/3.11.8/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/openedx/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/openedx/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/lms/djangoapps/course_home_api/outline/views.py", line 249, in get
    course_blocks = get_course_outline_block_tree(request, course_key_string, request.user)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/openedx/core/lib/cache_utils.py", line 74, in decorator
    result = wrapped(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/openedx/features/course_experience/utils.py", line 94, in get_course_outline_block_tree
    all_blocks = get_blocks(
                 ^^^^^^^^^^^
  File "/openedx/edx-platform/lms/djangoapps/course_api/blocks/api.py", line 122, in get_blocks
    blocks = course_blocks_api.get_course_blocks(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/lms/djangoapps/course_blocks/api.py", line 107, in get_course_blocks
    return get_block_structure_manager(starting_block_usage_key.course_key).get_transformed(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/manager.py", line 80, in get_transformed
    transformers.transform(block_structure)
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/transformers.py", line 114, in transform
    self._transform_without_filters(block_structure)
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/transformers.py", line 140, in _transform_without_filters
    transformer.transform(self.usage_info, block_structure)
  File "/openedx/edx-platform/lms/djangoapps/course_blocks/transformers/hidden_content.py", line 95, in transform
    block_structure.remove_block_traversal(lambda block_key: self._is_block_hidden(block_structure, block_key))
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/block_structure.py", line 704, in remove_block_traversal
    self.filter_topological_traversal(
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/block_structure.py", line 729, in filter_topological_traversal
    for _ in self.topological_traversal(filter_func=filter_func, **kwargs):
  File "/openedx/edx-platform/openedx/core/lib/graph_traversals.py", line 329, in _traverse_generic
    should_yield_node = filter_func(current_node)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/block_structure.py", line 685, in retain_or_remove
    if removal_condition(block_key):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/lms/djangoapps/course_blocks/transformers/hidden_content.py", line 95, in <lambda>
    block_structure.remove_block_traversal(lambda block_key: self._is_block_hidden(block_structure, block_key))
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/lms/djangoapps/course_blocks/transformers/hidden_content.py", line 103, in _is_block_hidden
    self_paced = block_structure[block_structure.root_block_usage_key].self_paced
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/openedx/core/djangoapps/content/block_structure/block_structure.py", line 306, in __getattr__
    raise AttributeError(f"Field {field_name} does not exist")  # lint-amnesty, pylint: disable=raise-missing-from
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Field self_paced does not exist
```